# Generated by Django 3.2.5 on 2021-07-14 19:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomName', models.CharField(default=None, max_length=500, primary_key=True, serialize=False)),
                ('roomOwnerGroup', models.CharField(default=None, max_length=500)),
                ('roomOwnerUserName', models.CharField(default=None, max_length=500)),
                ('userNames', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=None, null=True, size=None)),
                ('userGroups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=None, size=None)),
                ('userNames_UserGroups_dict', models.JSONField(default=None)),
                ('userNames_ChannelName_dict', models.JSONField(default=None)),
                ('teamName_leadersUserName_dict', models.JSONField(default=None, null=True)),
                ('teamName_MembersUserName_dict', models.JSONField(default=None, null=True)),
                ('userName_teamName_dict', models.JSONField(default=None, null=True)),
                ('member_count', models.IntegerField(default=1)),
                ('gameStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
