# Generated by Django 3.2.5 on 2021-07-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='dayStat',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='fishCount',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='fishScore',
            field=models.JSONField(default=None, null=True),
        ),
    ]
